console_title_template = "{{ .UserName }}@{{.HostName }} :: {{.Folder}}"
terminal_background = "transparent"
version = 3
final_space = true

[palette]
  blue-bell = "#9aa5ce"
  blue-black = "#565f89"
  celeste-blue = "#b4f9f8"
  light-sky-blue = "#7dcfff"
  main-bg = "#24283b"
  pastal-grey = "#cfc9c2"
  pistachio-green = "#9ece6a"
  t-background = "p:main-bg"
  terminal-black = "#414868"
  terminal-blue = "#7aa2f7"
  terminal-green = "#73daca"
  terminal-magenta = "#bb9af7"
  terminal-red = "#f7768e"
  terminal-white = "#c0caf5"
  terminal-yellow = "#e0af68"
  white-blue = "#a9b1d6"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "➜ "
    foreground = "p:terminal-blue"
    background = "transparent"
    type = "text"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
    template = "{{ .UserName }}@{{.HostName }} "
    foreground = "p:terminal-yellow"
    background = "transparent"
    type = "text"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
    template = "<b>{{ .Path }}</b> <p:light-sky-blue>⚡</>"
    foreground = "p:terminal-magenta"
    type = "path"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
      style = "folder"

  [[blocks.segments]]
    template = "({{ .HEAD}})"
    foreground = "p:light-sky-blue"
    type = "git"
    style = "plain"
    foreground_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}", "{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}", "{{ if gt .Behind 0 }}p:celeste-blue{{ end }}"]

    [blocks.segments.properties]
      branch_icon = " "
      cache_duration = "none"
      fetch_status = true

  [[blocks.segments]]
    template = " "
    foreground = "p:terminal-red"
    type = "status"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"

[[blocks]]
  type = "prompt"
  alignment = "right"
  overflow = "hide"

  [[blocks.segments]]
    foreground = "p:white-blue"
    type = "command"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
      command = "git log --pretty=format:%cr -1 || date +%H:%M:%S"
      shell = "bash"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "▶"
    foreground = "p:pistachio-green"
    type = "text"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
